#:schema node_modules/wrangler/config-schema.json
name = "analytics-engine-repro"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "ae_repro"

[triggers]
crons = [ "*/1 * * * *" ]
